config/routes.rb
THEMAN::Application.routes.draw do
  
  resources :programas

  match "/programas/questions" => "programas#questions", :as => :initial
  match "/programas/result" => "programas#result", :as => :result
  match "/programas/result2" => "programas#result2", :as => :result2
  match "/search" => "programas#search", :as => :search
  
  
  root :to => 'programas#questions'

end

app/models/programa.rb
class Programa < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/programas_controller.rb
class ProgramasController < ApplicationController
  # GET /programas
  # GET /programas.json
  @choice
  def index
    @programas = Programa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @programas }
    end
  end
  
  def questions

  end

  def search
        @programas = Programa.find(:all, :conditions => ['title LIKE ?', "%#{params[:search]}%"])
  end
  

  def result
    @choice = params[:my_choice]
    @programas = Programa.find(:all, :conditions => ['categoria LIKE ?', "%#{params[:my_choice]}%"])
  end

  def result2
    @programas = Programa.find(:all, :conditions => ["categoria=? and categoria2=?", "#{params[:my_choice]}", "#{params[:my_choice2]}"])
  end
  
  # GET /programas/1
  # GET /programas/1.json
  def show
    @programa = Programa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @programa }
    end
  end

  # GET /programas/new
  # GET /programas/new.json
  def new
    @programa = Programa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @programa }
    end
  end

  # GET /programas/1/edit
  def edit
    @programa = Programa.find(params[:id])
  end

  # POST /programas
  # POST /programas.json
  def create
    @programa = Programa.new(params[:programa])

    respond_to do |format|
      if @programa.save
        format.html { redirect_to @programa, :notice => 'Programa was successfully created.' }
        format.json { render :json => @programa, :status => :created, :location => @programa }
      else
        format.html { render :action => "new" }
        format.json { render :json => @programa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /programas/1
  # PUT /programas/1.json
  def update
    @programa = Programa.find(params[:id])

    respond_to do |format|
      if @programa.update_attributes(params[:programa])
        format.html { redirect_to @programa, :notice => 'Programa was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @programa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /programas/1
  # DELETE /programas/1.json
  def destroy
    @programa = Programa.find(params[:id])
    @programa.destroy

    respond_to do |format|
      format.html { redirect_to programas_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>THEMAN</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/programas/_form.html.erb
<%= form_for(@programa) do |f| %>
  <% if @programa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@programa.errors.count, "error") %> prohibited this programa from being saved:</h2>

      <ul>
      <% @programa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br />
    <%= f.select :categoria, ([["Yes", "Yes"], ["No", "No"]]) %>
  </div>
  <div class="field">
    <%= f.label :categoria2 %><br />
    <%= f.select :categoria2, ([["Yes", "Yes"], ["No", "No"]]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programas/edit.html.erb
<h1>Editing programa</h1>

<%= render 'form' %>

<%= link_to 'Show', @programa %> |
<%= link_to 'Back', programas_path %>

app/views/programas/index.html.erb
<h1>Listing programas</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Categoria</th>
    <th>Categoria2</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @programas.each do |programa| %>
  <tr>
    <td><%= programa.title %></td>
    <td><%= programa.categoria %></td>
    <td><%= programa.categoria2 %></td>
    <td><%= link_to 'Show', programa %></td>
    <td><%= link_to 'Edit', edit_programa_path(programa) %></td>
    <td><%= link_to 'Destroy', programa, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Programa', new_programa_path %>

app/views/programas/new.html.erb
<h1>New programa</h1>

<%= render 'form' %>

<%= link_to 'Back', programas_path %>

app/views/programas/questions.html.slim
p O lugar pra onde você vai tem Bebida?

= form_for :aaaa, :url => result_path do 

  select#option name="my_choice"
    option Yes 
    option No
  
  input type="submit" value="Answer"
  
= button_to 'Busca de texto', :action => :search

app/views/programas/result.html.slim
p O lugar pra onde você vai tem Musica?

= form_for :aaaa2, :url => result2_path do 

  select#option name="my_choice2"
    option Yes
    option No
    
  input type="hidden" name="my_choice" value=@choice
  
  input type="submit" value="Answer"
  
=button_to 'Busca de texto', :action => :search
  
h1 Resultados
ul
- @programas.each do |programa|
  li = programa.title

app/views/programas/result2.html.slim
= button_to 'Busca de texto', :action => :search
= button_to 'Nova sugestão', :action => :questions

br

h1 Resultados

ul
- @programas.each do |programa|
  li = programa.title

app/views/programas/search.html.slim
= button_to 'Receber Sugestão', :action => :questions

h1 Busca do Cara 

= form_for :aaaa, :url => search_path do
  input type="text" name="search" 
 
  input type="submit" value="Buscar!"

ul
  - if params[:search] != nil && params[:search] != ""
    h1 Resultados
    - if @programas == []
      p Nao encontrei nenhum resultado
    - @programas.each do |programa|
      li = programa.title
      
- # debug @programas
- # p = @programas

app/views/programas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @programa.title %>
</p>

<p>
  <b>Categoria:</b>
  <%= @programa.categoria %>
</p>

<p>
  <b>Categoria2:</b>
  <%= @programa.categoria2 %>
</p>



<%= link_to 'Edit', edit_programa_path(@programa) %> |
<%= link_to 'Back', programas_path %>